# Generated by Django 5.0.6 on 2024-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_alter_candidature_date_de_soumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='formation3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='formation5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='formation6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='formation2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='formation4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='formation7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='formation8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='universite8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
