# Generated by Django 5.0.6 on 2024-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_candidature_formation3_candidature_formation5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='formation1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
