# Generated by Django 4.0.3 on 2024-06-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='université',
            name='photo',
        ),
    ]
