# Generated by Django 4.0.3 on 2024-05-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='université',
            name='FAX',
        ),
        migrations.AddField(
            model_name='université',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='universite_photos/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_agent',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='Formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.formation'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='Spécialité',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.spécialité'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='Université',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.université'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='id_candidature',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Date_de_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='id_etudiant',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formation',
            name='Coût_de_formation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='formation',
            name='Durée',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='id_formation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pays',
            name='id_pays',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spécialité',
            name='id_spécialité',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='université',
            name='id_univ',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
