# Generated by Django 5.0.6 on 2024-06-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_université_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='id_université',
        ),
    ]
