# Generated by Django 4.0.3 on 2024-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_formation_id_université'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='formation1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status1',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status2',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status3',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status4',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status5',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status6',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status7',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status8',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=50),
        ),
    ]
