# Generated by Django 5.0.6 on 2024-06-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_candidature_formation1_alter_candidature_status1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidature',
        ),
    ]
